# Copyright (C) 2022 Sebastian Thomschke and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.md'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install python dependencies
      run: |
        set -eux

        python --version

        python -m pip install --upgrade pip

        pip install pdm
        pip install pdm-packer

        # https://github.com/python/mypy/issues/11829
        pip install -t __pypackages__/3.10/lib git+git://github.com/python/mypy.git@9b3147701f054bf8ef42bd96e33153b05976a5e1

        # https://github.com/pdm-project/pdm/issues/728#issuecomment-1021771200
        pip install -t __pypackages__/3.10/lib selenium

        pdm install

    - name: Scanning for security issues using bandit
      run: |
        pdm run bandit

    - name: pylint
      run: |
        pdm run pylint

    - name: pytest
      run: |
        pdm run pytest

    - name: run kleinanzeigen_bot
      run: |
        echo "
        login:
          username: 'john.doe@example.com'
          password: 'such_a_secret'
        " > config.yaml

        set -eux

        pdm run app help
        pdm run app version
        pdm run app verify

    - name: "Build docker image"
      if: startsWith(matrix.os, 'linux')
      run: |
        set -eux

        bash docker/build-image.sh

        docker run --rm kleinanzeigen-bot/kleinanzeigen-bot help

    - name: "Install: binutils (strip)"
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get --no-install-recommends install -y binutils

    - name: "Install: UPX"
      run: |
        set -eu
        
        case "${{ matrix.target }}" in
          macos-*)
            brew install upx
            ;;
          ubuntu-*)
            mkdir /opt/upx
            upx_download_url=$(curl -fsSL https://api.github.com/repos/upx/upx/releases/latest | grep browser_download_url | grep amd64_linux.tar.xz | cut "-d\"" -f4)
            echo "Downloading [$upx_download_url]..."
            curl -fL $upx_download_url | tar Jxv -C /opt/upx --strip-components=1
            echo "/opt/upx" >> $GITHUB_PATH
            ;;
          windows-*)
            upx_download_url=$(curl -fsSL https://api.github.com/repos/upx/upx/releases/latest | grep browser_download_url | grep win64.zip | cut "-d\"" -f4)
            echo "Downloading [$upx_download_url]..."
            curl -fL -o /tmp/upx.zip $upx_download_url
  
            echo "Extracting upx.zip..."
            mkdir /tmp/upx
            7z e /tmp/upx.zip -o/tmp/upx *.exe -r
            echo "$(cygpath -wa /tmp/upx)" >> $GITHUB_PATH
            ;;
        esac
        

    - name: pyinstaller
      run: |
        set -eux
        
        pdm run pyinstaller
        
        ls -l dist

    - name: run kleinanzeigen_bot.exe
      if: startsWith(matrix.os, 'windows')
      run: |
        set -eux

        dist/kleinanzeigen-bot.exe help
        dist/kleinanzeigen-bot.exe version
        dist/kleinanzeigen-bot.exe verify

    - name: "Delete previous 'latest' release"
      if: startsWith(matrix.os, 'windows') && github.ref == 'refs/heads/main'
      run: |
        set -eu

        api_base_url="$GITHUB_API_URL/repos/$GITHUB_REPOSITORY"

        # delete 'latest' github release
        release_id=$(curl -fsL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq -r '.[] | select(.name == "latest") | .id')
        if [[ -n $release_id ]]; then
           echo "Deleting release [$api_base_url/releases/$release_id]..."
           curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -fsSL -X DELETE "$api_base_url/releases/$release_id"
        fi

        # delete 'latest' git tag
        tag_url="$api_base_url/git/refs/tags/latest"
        if curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -fsLo /dev/null --head "$tag_url"; then
           echo "Deleting tag [$tag_url]..."
           curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -fsSL -X DELETE "$tag_url"
        fi

    - name: "Create 'latest' Release"
      if: startsWith(matrix.os, 'windows') && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -eux

        # https://hub.github.com/hub-release.1.html
        hub release create "latest" \
          --prerelease \
          --message "latest" \
          --attach "dist/kleinanzeigen-bot.exe#kleinanzeigen-bot.exe"

    - name: "Delete intermediate build artifacts"
      uses: geekyeggo/delete-artifact@1-glob-support # https://github.com/GeekyEggo/delete-artifact/
      with:
        name: "*"
        useGlob: true
        failOnError: false
